### ISSUE TITLE
Breaking changes for v5

### ISSUE THREAD

**Issue by josdejong** [josdejong/mathjs#1045]
We'll collect any breaking changes we want to do in this issue.

- [x] More consistent behavior of sqrt, nthRoot, and pow. See #851, #1060 
- [x] Change transpose operator `A'` to calculate `ctranspose`, see #1094, #1097
- [x] Rename `math.eye` to `math.identity`. See #1054
- [x] Upgrade (breaking) dependencies
- [x] Drop the `dist` folder from the git repo. This was needed for bower support, but bower is deprecated now. 
- [x] Implement a build script to allow using ES6. See #914.
- [x] Set up linter #1110

If you know of more breaking changes we should address, please let me know.

**Comment by josdejong** [comment]
I moved the topic of #864 to breaking changes for v6 #1127, it's time to move ahead with v5

**Comment by josdejong** [comment]
I will move the `v5` branch into `develop` today, the next release will be `v5`

**Comment by josdejong** [comment]
Yes, I first have to merge develop into v5 again, it's a bit behind

**Comment by harrysarson** [comment]
If you look at https://unpkg.com/mathsjs/ you can see everything that gets downloaded when you run `npm install mathjs`, this means folt are downloading fra more than they need if they just want to include mathjs as a dep or run the CLI.

**Comment by josdejong** [comment]
Ah, that's a good point! We should indeed remove the test folders from the npm package.

**Comment by harrysarson** [comment]
See #1128

**Comment by josdejong** [comment]
I will release v5.0.0 tomorrow.

**Comment by josdejong** [comment]
Release will be tomorrow or coming weekend: fully finished #1110 (more than expected) but no time left today to do the release.

**Comment by harrysarson** [comment]
see #1115 about dropping  support for IE 9.

Would be a small and doc only change.

**Comment by josdejong** [comment]
@harrysarson I've updated the docs: https://github.com/josdejong/mathjs/commit/4ca1d563b8aad2a439507e60a279842f365a9f29

**Comment by josdejong** [comment]
Just released `v5.0.0` :tada:
