### ISSUE TITLE
Breaking changes for v8

### ISSUE THREAD

**Issue by josdejong** [josdejong/mathjs#1960]
- [x] Full support for ES modules, see #1941, #1962.
- [x] Fix an issue in `pickRandom`, see #1990 and https://github.com/josdejong/mathjs/pull/1976#issuecomment-711133172.
- [x] Replace `seed-random` library with `seedrandom`, see #1955.
- [x] Think through whether actually wanting to run the unit tests without transpilation. This requires all imports to use actual paths, including name extension `*.js`. However, most peoples IDE's are not configured to do that with auto imports. How can we prevent this from becoming a big frustration point?

The issue #864 is (still) not going to make it in v8.

**Comment by josdejong** [comment]
I've just published `v8.0.0-beta.0`.

**Comment by josdejong** [comment]
`v8.0.0` has been published now 🎉
