### ISSUE TITLE
v14 breaking changes

### ISSUE THREAD

**Issue by josdejong** [josdejong/mathjs#3209]
This issue will keep track on breaking changes planned for mathjs `v14`. Please comment if there are more topics to discuss.

- [x] [3225](https://github.com/josdejong/mathjs/discussions/3225) prevent `math.import(...)` from overriding units unless you specify `{ override: true }`. See [3222](https://github.com/josdejong/mathjs/discussions/3222)
- [x] [#3283](https://github.com/josdejong/mathjs/pull/3283) Upgrade to `fraction.js@5`, using `bigint` under the hood 
- [x] [3269](https://github.com/josdejong/mathjs/pull/3269) Possible breaking changes in changing the type definitions of arrays and matrices to generics.
- [x] [#3260](https://github.com/josdejong/mathjs/discussions/3260) think through changing the `index` in the `filter` callback to be a number instead of an array holding one number since `filter` only supports 1d arrays.
- [x] [#3307](https://github.com/josdejong/mathjs/pull/3307) let functions like `dotDivide` return a sparse matrix when the input is two sparse matrices.
- [x] [#3306 ](https://github.com/josdejong/mathjs/pull/3306) improve type definitions of arrays
- [x] [#3311](https://github.com/josdejong/mathjs/pull/3311) fix precedence of `%` (mod) being higher than `*` and `/`

**Comment by iJhefe** [comment]
I've been thinking about the promises support. Perhaps we could get some of the old and new discussions and work on it in this release or a next one?

**Comment by josdejong** [comment]
Definitely!

**Comment by josdejong** [comment]
I've introduced a new milestone ["one day"](https://github.com/josdejong/mathjs/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22one+day%22) and move the big refactor plans there, since we don't know when that will be ready.

**Comment by dvd101x** [comment]
Hi Jos,

Regarding #3260 I noticed that one of the taks mentions the `forEach` function but I guess you meant `filter`.

**Comment by josdejong** [comment]
@dvd101x ah, yes, thanks. I fixed the typo.

**Comment by josdejong** [comment]
Version 14 is now published 🎉, closing this topic now.
